### ISSUE TITLE
Link between epi2me-labs / pore-c-py and epi2me-labs / wf-pore-c

### ISSUE THREAD

**Issue by s4251484** [epi2me-labs/pore-c-py#1]
Hi 
Are epi2me-labs/pore-c-py and epi2me-labs/wf-pore-c different?
how can we use either one or both for pore-c analysis?
Do you have a recommended workflow?

**Comment by cjw85** [comment]
`pore-c-py` is a set of Python tools for preprocessing sequencing read data from the Pore-C protocol. `wf-pore-c` uses to `pore-c-py` to process data at scale in a recommended fashion.
