### ISSUE TITLE
Adjust the name of monomer/walk tag in digest to compatibility with pairtools

### ISSUE THREAD

**Issue by LuJiansen** [epi2me-labs/pore-c-py#10]
Hi, I'm trying to convert the pore-c-py digested bam into .pairs format and extract the SAM tags including monomer tag `Xc` and walk tag `Xw` as extra column in the .pairs file. However, the pairtools only supports SAM tag with pair of uppercase letters. Could you please adjust the name of these tags of give a option for users to define them? Thanks!

**Comment by cjw85** [comment]
The lowecase letters indicate that these tags are not formally defined by the Sam tags specification. They are deliberately not uppercase. See https://samtools.github.io/hts-specs/SAMtags.pdf

In that sense this is a bug in pairtools not pore-c-py.

**Comment by LuJiansen** [comment]
Thank you for your prompt reply!
