### ISSUE TITLE
filter_pairs

### ISSUE THREAD

**Issue by ilead-cong** [epi2me-labs/pore-c-py#11]
hi!

I have a question about annotate_bam. The two parameters paired_end_minimum_distance and paired_end_maximum_distance do not work. In the code below, the default parameters in the definition of the function filter_pairs are as follows: min_distance=0, max_distance=float("inf"). Is there any other place to define them?

![image](https://github.com/user-attachments/assets/29fce8dc-4127-43c0-a08e-33c1e197b7f0)

**Comment by sarahjeeeze** [comment]
Hi, this is an oversight - we will look at reinstating these filter options.

**Comment by sarahjeeeze** [comment]
Closing for now but we have an internal ticket to look in to this and add a fix. But no timeline currently.
