### ISSUE TITLE
Testing Data for Workflow Learning

### ISSUE THREAD

**Issue by biozzq** [epi2me-labs/pore-c-py#13]
Hi，

Could you please let me know if there are any available raw signal data (.pod5) that I could use for practice? I am eager to see how well the process handles this issue (https://github.com/nanoporetech/modkit/issues/289), and having access to such data would be immensely helpful.

Thank you very much for your assistance!

Best regards,
Zheng zhuqing

**Comment by sarahjeeeze** [comment]
Some is linked here https://labs.epi2me.io/mod-validation-data/
