### ISSUE TITLE
"conda install -c epi2me-labs pore-c-py" does not work

### ISSUE THREAD

**Issue by jianglinghan** [epi2me-labs/pore-c-py#2]
`conda install -c epi2me-labs pore-c-py` does not work,
`conda install -c epi2melabs  pore-c-py`  works

**Comment by SamStudio8** [comment]
@jianglinghan Sorry for the delayed response, thank you for pointing out this error in our documentation. `pore-c-py` is now available from the `nanoporetech` channel, I will update the README.
