### ISSUE TITLE
Request for Information on Human Breast Cancer Cell Line

### ISSUE THREAD

**Issue by zhijs** [epi2me-labs/pore-c-py#3]
Hello,

First of all, I would like to thank you for your excellent project and the tools you have provided. I am interested in using the Pore-C data of human breast cancer cells and would like to gather more details about this cell line, such as information on the human group (e.g., the number of individuals involved).

I found the code (ATCC, CRL-2388) for the cell line in your article, but I have been unable to locate the specific information on the [ATCC website](https://www.atcc.org/). I understand that you are quite busy, but I would be truly grateful for any help or guidance you can offer on this matter. Thank you in advance for your time and consideration.

Best regards.

zhijs

**Comment by cjw85** [comment]
Please direct your request to support@nanoporetech.com. The developers of this software cannot assist in your request.
