### ISSUE TITLE
CIGAR and query sequence lengths differ

### ISSUE THREAD

**Issue by yangxin-9** [epi2me-labs/pore-c-py#5]
Hello,
    I've been trying to use annotate using pore-c-py.
    I managed to use the script you recommend from [here](https://github.com/epi2me-labs/pore-c-py).
   However, after running the following command, the error below pops-up:
    pore-c-py annotate --stdout True --threads 10 --monomers 10U_ON_chunk.digest.bam *_anno ,

[E::idx_find_and_load] Could not retrieve index file for '10U_ON_chunk.digest.bam'
[E::bam_read1] CIGAR and query sequence lengths differ ... ...

Any suggestions? My guess digest truncate the read in bam file, the read length of the new record in bam file is not consistent with the original length.I wonder if it is my improper use of the software? Is there a detailed tutorial you can refer to?

Thanks

**Comment by cjw85** [comment]
Hi @yangxin-9,

We do not have a full tutorial as the project was created for use within our [wf-pore-c](Https://GitHub.com/epi2me-labs/wf-pore-c) workflow.

I'm going to guess here that you have started from a BAM with alignments stored, before running the `digest` command? And then tried to run the `annotate` command on the result? Correct usage requires passing the output of the `digest` command to an aligner.

**Comment by yangxin-9** [comment]
Okay thanks .  Yes , i have started from the alignments stored BAM file. Then I know how to handle these.

Your reply was very helpful to me!

Thanks
