### ISSUE TITLE
Please provide current run command line run instructions

### ISSUE THREAD

**Issue by ahcm** [epi2me-labs/pore-c-py#7]
Hi,

The commandline workflow posted in the other bug report has issues.
But note, it is rather simple and would be sufficient for most people.
It is much easier to get to work this than installing all the tools (nextflow, singularity, java etc.) that are need for your epi2me workflow.
Also then the epi2me workflow just dies because the java (who still runs java ?!?) does not get enough RAM (the server has a lot, 2TB, so I assume, the jvm is not getting enough from the caller in the workflow).

Further, since pore-c ist still in the beginning and undergoing a lot of changes in the analysis pipeline, I would rather prefer to report the actual commands and versions in a paper than to refer to a mystical epi2me workflow.

So I would ask that you keep and up to date version (e.g. simple, with pipes, like in the other bug report) in the README.md.

Thansk a lot!
Andy

**Comment by cjw85** [comment]
Hi Andreas,

If you are shocked to find that nextflow uses Java, you'll be more shocked to find that its actually written in Groovy! If I recall correctly the workflow doesn't use Java (certainly not at the point that it is going awry). I suspect it is the JVM running nextflow itself that is struggling not something internal to workflow tasks.

I have added a more fulsome example to the README.

**Comment by ahcm** [comment]
Thanks a lot!
This is running fine, besides that --stdout needs to be changed to --stdout true (imo should be a simple flag like you used in your example but ...).

**Comment by cjw85** [comment]
This was changed in the release I made this afternoon.

**Comment by ahcm** [comment]
$ samtools index all.ns.bam
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
[E::hts_idx_push] NO_COOR reads not in a single block at the end 68 -1
[E::sam_index] Read 'dced7971-54a8-4925-8ece-23da32c5131c:0403:0563' with ref_name='contig_105', ref_length=89711338, flags=16, pos=60491129 cannot be inde
xed
samtools index: failed to create index for "all.ns.bam": No such file or directory

Also how would the downstream analysis work?
I tried:
`yahs all.cs.bam myref.fasta`
But it segfaults.

**Comment by cjw85** [comment]
The error:

```[W::bam_hdr_read] EOF marker is absent. The input is probably truncated```

would suggest that all.ns.bam is currupt or incomplete. Without seeing the output from when that file was produced I cannot suggest why that would be the case.

I'm not familiar enough with yahs to comment beyond suspecting its seqfaulting because your all.cs.bam is similarly truncated.
